/* Generated By:JavaCC: Do not edit this line. BinaryParserConstants.java */
package genParser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BinaryParserConstants {

  /** End of File. */
  int EOF = 0;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\";\"",
    "\"0\"",
    "\"1\"",
  };

}
